apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306

---
# storage request: PVC is independent of the pod life cycle and preserves the pod data if a pod crash
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: services/mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:               # we use a storage volume to persist the data  
        - mountPath: /var/lib/mysql 
          name: mysql-pvc
          subPath: mysql
        livenessProbe:
          exec:
            command:
              - sh
              - liveness_probe.sh
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc

