apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050 
    targetPort: 5050
    name: wordpress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: services/wordpress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
              - sh
              - liveness_probe.sh
          initialDelaySeconds: 10
          periodSeconds: 5