apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  type: LoadBalancer 
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 20
    targetPort: 20
    name: ftps-data
  - port: 21000
    targetPort: 21000
    name: ftps-datarange
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: services/ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 20
          name: ftps-data
        - containerPort: 21000
          name: ftps-datarange
        livenessProbe:
          exec:
            command:
              - sh
              - liveness_probe.sh
          initialDelaySeconds: 10
          periodSeconds: 5
